import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import KeelAuthProvider from "./keel";
import { KeelProvider } from "./keel/keel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SignedIn>
        <KeelProvider baseUrl={process.env.API_BASE_URL!}>
          <KeelAuthProvider>
            <html>
              <body>
                {children}
              </body>
            </html>
          </KeelAuthProvider>
        </KeelProvider>
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>

    </ClerkProvider>
  );
}
