# See https://docs.keel.so/envvars for more info
environment:

# # See https://docs.keel.so/secrets for more info
secrets:

auth:
  providers:
    - type: oidc
      name: clerk
      issuerUrl: "https://famous-mite-19.clerk.accounts.dev" # Your Clerk url
      clientId: "keel" # Must match the Clerk JWT aud claim
